""""
Exercise 18 (and Solution)

Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a “cow”. 
For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...

Until the user guesses the number.

-> LESSONS LEARNED: Lists are mutable and get modified when passed to a function!
"""

import random


# Modules

def cows_and_bulls(num: list, g: list):

    temp_num = num.copy() # This is to not change the original number when mascin out the correct guesses.
    cows = 0
    bulls = 0
    i = 0

    # Filter out all cows and replace with X so the don't get counted when looking for bulls
    while i < 4:
        if temp_num[i] == g[i]:
            cows += 1
            temp_num[i] = "x"
            i += 1
        else:
            i += 1

    i = 0
    
    # Filter for bulls. On first hit replace with x so it won't get counted twice.
    while i < 4:
        if g[i] in temp_num:
            bulls += 1
            temp_num[temp_num.index(g[i])] = "x"
            i += 1
        else:
            i += 1
   
    return cows, bulls


# Main

def main():

    game = 1
    trys = 0
    number = list(str(random.randint(1000,9999)))
    a = number
    
    print(
        "Welcome to the cows and bulls game. For every digit that you guessed correctly in the correct place, you have a “cow”.\n"
        "For every digit the user guessed correctly in the wrong place is a “bull.” ")
        
    while game:
        print(a)
        guess = list(str(input("Make your Guess:\n")))
        trys += 1
        cows, bulls = cows_and_bulls(a, guess)
        print("{} cows, {} bulls.".format(cows, bulls))
        if cows == 4:
            game = 0
    
    print("Thanks for playing. You guessed {} times".format(trys))


if __name__ == "__main__":
    main()